= springboot
meguru <764904418@qq.com>
v1.0, 2020-10-25
:toc:
:toc-title: 目录
:toclevels: 5

== springboot 代码学习

'''

=== springboot modules

* *spring-boot*

* *spring-boot-autoconfigure*

* *spring-boot-starters*

* *spring-bootcli*

* *spring-boot-actuator*

* *spring-boot-actuator-autoconfigure*

* *spring-boot-test*

* *spring-boot-test-autoconfigure*

* *spring-boot-loader*

* *spring-boot-devtools*

== springboot 应用学习

'''

=== CommandLineRunner

实现CommandLineRunner接口并重写run方法的**bean**，在spring项目启动后，自动执行run方法。

https://docs.spring.io/spring-boot/docs/current/api/[doc]
https://github.com/spring-projects/spring-boot/blob/2.3.x/spring-boot-tests/spring-boot-smoke-tests/spring-boot-smoke-test-aop/src/main/java/smoketest/aop/SampleAopApplication.java[example]

'''

=== WebApplicationType

SpringApplication启动时，会推论出应用程序的类型，默认是none，当引入org.springframework.boot:spring-boot-starter-web时，类加载器中会有class文件org.springframework.web.context.ConfigurableWebApplicationContext，此时应用程序类型为servlet

[source,java]
.WebApplicationType.java
----
static WebApplicationType deduceFromClasspath() {
		if (ClassUtils.isPresent(WEBFLUX_INDICATOR_CLASS, null) && !ClassUtils.isPresent(WEBMVC_INDICATOR_CLASS, null)
				&& !ClassUtils.isPresent(JERSEY_INDICATOR_CLASS, null)) {
			return WebApplicationType.REACTIVE;
		}
		for (String className : SERVLET_INDICATOR_CLASSES) {
			if (!ClassUtils.isPresent(className, null)) {
				return WebApplicationType.NONE;
			}
		}
		return WebApplicationType.SERVLET;
	}
----


https://github.com/spring-projects/spring-boot/blob/2.3.x/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/WebApplicationType.java[WebApplicationType.java]

'''

=== ApplicationEvent

==== SpringApplicationEvent

===== ApplicationStartingEvent

'''

=== ApplicationEventMulticaster

== springboot 实践

'''

=== 使用JavaMailSender发送邮件

[source,java]
.MailHelper.java
----
@Slf4j
public class MailHelper {

    @Autowired
    private JavaMailSender sender;


    public void sendWithMultipart(String from, String to, String subject, String text, String attachmentFilename, byte[] data) throws MessagingException {
        MimeMessage message = sender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message, true);
        helper.setFrom(from);
        helper.setTo(to);
        helper.setSubject(subject);
        helper.setText(text);
        ByteArrayDataSource byteArrayDataSource = new ByteArrayDataSource(data, "application/octet-stream");
        try {
            attachmentFilename = MimeUtility.encodeWord(attachmentFilename, "UTF-8", "B");
        } catch (UnsupportedEncodingException e) {
            log.error("attachment file name encode error ", e);
        }
        helper.addAttachment(attachmentFilename, byteArrayDataSource);
        sender.send(message);
    }

}
----

[NOTE]
====
附件名称需要转码
====

'''

=== springboot的秒表计时器StopWatch

